### PR TITLE
#1 Change imports to relative to expose main function

### PR DESCRIPTION
**Pull request by franomai**
Here are the changes I made to the imports to get the main export in` __init__` to work.  The relative imports did not work with the config path check in [accept_reject.py](https://github.com/riverscuomo/new-albums/compare/e0637a34eed9c0613616091209b01cd62b016f0a...7218deca746081f25ebf2e4defebd0d68c8c186f#diff-8bf172fdbb8edaf854d44776727e0f6e76bc5713ea4e450ab1313f4ab19a4da7), so I have updated it to take the path where the current code is, which I believe should give the same result. Please verify this is working as expected, because my local env stops at the Spotify verification!

### CODE REVIEW

**Comment by franomai** [comment]
Hope this PR works as expected and shows the changes - not sure how it interacts with submodules. Verified this locally by running both` py maintenance.py -m new_albums` and `py -m new_albums`. There is a new warning on the latter:

<frozen runpy>:128: RuntimeWarning: 'new_albums.__main__' found in sys.modules after import of package 'new_albums', but prior to execution of 'new_albums.__main__'; this may result in unpredictable behaviour

I am not sure if this is avoidable, and more generally, if the change made is best practice. Hopefully someone more familiar with Python modules can review.

**Comment by riverscuomo** [comment]
Hmm... I'm still getting no attribute 'main'

image

Let me dig into Brett's suggestions.

**Comment by franomai** [comment]
@riverscuomo - That's strange! Can you double check that the new_albums submodule has these updates on your local copy, and that you get the warning when you rerun it directly? You should see that the `__init__` in the new_albums\new_albums folder is now `from .__main__ import main` -  here is what I get from `py maintenance.py -m new_albums` and `py -m new_albums` respectively.

image
image

**Comment by franomai** [comment]
Have made a PR to the other repo to test just in case. Happy to revisit if it is still not working after that.

**Pull request merged**
